# CẤU HÌNH SERVER
server.port=8080

# CẤU HÌNH OPENROUTER AI
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.api.key=${AI_API_KEY}

# TÊN MODEL AI Chatbot:
openrouter.api.model=arcee-ai/trinity-large-preview:free
