server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/nutrisnap_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tho17092004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CẤU HÌNH OPENROUTER AI
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions

# ĐIỀN API KEY CỦA BẠN VÀO ĐÂY (Nếu chưa có, hãy đăng ký tạm trên openrouter.ai)
openrouter.api.key=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

# TÊN MODEL AI:
openrouter.api.model=arcee-ai/trinity-large-preview:free